name: lyabao
dependencies:
- !!python/unicode
  'astropy=1.3=np112py27_0'
- !!python/unicode
  'h5py=2.6.0=np112py27_2'
- !!python/unicode
  'matplotlib=2.0.0=np112py27_0'
- !!python/unicode
  'numpy=1.12.0=py27_0'
- !!python/unicode
  'pip=9.0.1=py27_1'
- !!python/unicode
  'python=2.7.13=0'
- !!python/unicode
  'scikit-learn=0.18.1=np112py27_1'
- !!python/unicode
  'scipy=0.18.1=np112py27_1'
- pip:
  - bossdata==0.2.8
  - fitsio==0.9.10
  - tqdm==4.11.2
